# Generated by Django 5.0.6 on 2024-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_image_alter_orderitems_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/no-image.png', upload_to='product/image'),
        ),
    ]
