# Generated by Django 5.0.6 on 2024-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(default='no-image.png', upload_to='category/image'),
        ),
    ]
