# Generated by Django 5.0.6 on 2024-07-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
