# Generated by Django 5.0.6 on 2024-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_product_price_alter_product_usd_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=83, max_digits=10),
        ),
    ]
