# Generated by Django 5.0.6 on 2024-07-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'customer address', 'verbose_name_plural': 'customer addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'order items'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name_plural': 'product ratings'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'wishlists'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_wishlist', to='ecommerce.customer'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_wishlist', to='ecommerce.product'),
        ),
    ]
