# Generated by Django 5.0.6 on 2024-07-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
