# Generated by Django 5.0.6 on 2024-08-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_alter_product_category_alter_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='customer/image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveBigIntegerField(max_length=12, null=True),
        ),
    ]
