# Generated by Django 5.0.6 on 2024-08-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='default_address',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
