# Generated by Django 5.0.6 on 2024-08-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_rename_vendor_seller_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_category', to='ecommerce.seller'),
        ),
    ]
