# Generated by Django 5.0.6 on 2024-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_productcategory_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR')], default='INR', max_length=3),
        ),
    ]
