# Generated by Django 5.0.6 on 2024-08-09 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stemp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
