# Generated by Django 5.0.6 on 2024-08-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_remove_product_customer_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
