# Generated by Django 5.0.6 on 2024-08-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_orderitems_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order_status',
        ),
    ]
