export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGUP_FAIL="SIGNUP_FAIL";
export const AUTHENTICATED_SUCCESS="AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAILED="AUTHENTICATION_FAILED";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGOUT="LOGOUT";