export const CUSTOMER_SIGNUP_SUCCESS="CUSTOMER_SIGNUP_SUCCESS";
export const CUSTOMER_SIGUP_FAIL="CUSTOMER_SIGNUP_FAIL";
export const CUSTOMER_AUTHENTICATED_SUCCESS="CUSTOMER_AUTHENTICATED_SUCCESS";
export const CUSTOMER_AUTHENTICATED_FAILED="CUSTOMER_AUTHENTICATION_FAILED";
export const CUSTOMER_LOGIN_SUCCESS="CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAIL="CUSTOMER_LOGIN_FAIL";
export const CUSTOMER_PROFILE_UPDATE_SUCCESS="CUSTOMER_PROFILE_UPDATE_SUCCESS";
export const CUSTOMER_PROFILE_UPDATE_FAILED="CUSTOMER_PROFILE_UPDATE_FAILED";

export const SELLER_SIGNUP_SUCCESS="SELLER_SIGNUP_SUCCESS";
export const SELLER_SIGUP_FAIL="SELLER_SIGNUP_FAIL";
export const SELLER_AUTHENTICATED_SUCCESS="SELLER_AUTHENTICATED_SUCCESS";
export const SELLER_AUTHENTICATED_FAILED="SELLER_AUTHENTICATION_FAILED";
export const SELLER_LOGIN_SUCCESS="SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL="SELLER_LOGIN_FAIL";
export const SELLER_PROFILE_UPDATE_SUCCESS="SELLER_PROFILE_UPDATE_SUCCESS";
export const SELLER_PROFILE_UPDATE_FAILED="SELLER_PROFILE_UPDATE_FAILED";

export const EMAIL_VERIFY_SUCCESS="EMAIL_VERIFY_SUCCESS";
export const EMAIL_VERIFY_FAILED="EMAIL_VERIFY_FAILED";
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED="CHANGE_PASSWORD_FAILED";
export const LOGOUT="LOGOUT";